before_install:
  - sudo apt install libcgal-dev libglu1-mesa-dev mesa-common-dev
language: r
r_packages:
  - betareg
  - e1071
  - gamlss
  - gamm4
  - gbm
  - lme4
  - locfit
  - mgcv
  - nnet
  - quantreg
  - randomForest
  - rgl
script:
  - R CMD build .
  - R CMD check *.tar.gz
