language: r
r_packages:
  - betareg
  - e1071
  - gamlss
  - gamm4
  - gbm
  - lme4
  - locfit
  - mgcv
  - nnet
  - quantreg
  - randomForest
warnings_are_errors: false
r_check_args: --test-dir=inst/tests
