# Site settings
title: visreg
version: 2.7.0
email: patrick-breheny@uiowa.edu
description: "visreg: An R package for the visualization of regression models"
github_username: pbreheny

# Build settings
markdown: kramdown
exclude: [Makefile, src, cache]
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
